version: '3.4'

services:
  healthminapi:
    image: ${DOCKER_REGISTRY-}healthminapi
    build:
      context: .
      dockerfile: HealthMinAPI/Dockerfile

  higheduminapi:
    image: ${DOCKER_REGISTRY-}higheduminapi
    build:
      context: .
      dockerfile: HighEduMinAPI/Dockerfile

