version: '3.4'

services:
  healthminapi:
    image: ${DOCKER_REGISTRY-}healthminapi
    build:
      context: .
      dockerfile: HealthMinAPI/Dockerfile

  higheduminapi:
    image: ${DOCKER_REGISTRY-}higheduminapi
    build:
      context: .
      dockerfile: HighEduMinAPI/Dockerfile


  airlineapi:
    image: ${DOCKER_REGISTRY-}airlineapi
    build:
      context: .
      dockerfile: AirLineAPI/Dockerfile


  politicalpartiesapi:
    image: ${DOCKER_REGISTRY-}politicalpartiesapi
    build:
      context: .
      dockerfile: PoliticalPartiesAPI/Dockerfile

