version: '3.4'

services:

  consul:
    image: consul:latest
    container_name: consul_server
    network_mode: bridge
    ports:
      - "8500:8500"
      -  "8600:8600/udp"
    command:  consul agent -dev -server -ui -node=server-1 -bootstrap-expect=1 -client="0.0.0.0"

  sql-server-db:
    container_name: SQL_Server
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sqlvol:/var/opt/mssql
    ports:
      - "1403:1433"
    environment:
      SA_PASSWORD: "r00t.R00T"
      ACCEPT_EULA: "Y"

  healthminapi:
    image: ${DOCKER_REGISTRY-}healthminapi
    build:
      context: .
      dockerfile: HealthMinAPI/Dockerfile
    ports:
      - "41003:80"
      - "40003:443"
  higheduminapi:
    image: ${DOCKER_REGISTRY-}higheduminapi
    build:
      context: .
      dockerfile: HighEduMinAPI/Dockerfile
    ports:
      - "41001:80"
      - "40001:443"


  airlineapi:
    image: ${DOCKER_REGISTRY-}airlineapi
    build:
      context: .
      dockerfile: AirLineAPI/Dockerfile
    ports:
      - "41002:80"
      - "40002:443"

  politicalpartiesapi:
    image: ${DOCKER_REGISTRY-}politicalpartiesapi
    build:
      context: .
      dockerfile: PoliticalPartiesAPI/Dockerfile
    ports:
      - "41004:80"
      - "40004:443"

  bloodbankapi:
    image: ${DOCKER_REGISTRY-}bloodbankapi
    build:
      context: .
      dockerfile: BloodBankAPI/Dockerfile
    ports:
      - "41005:80"
      - "40005:443"

  universityapi:
    image: ${DOCKER_REGISTRY-}universityapi
    build:
      context: .
      dockerfile: UniversityAPI/Dockerfile
    ports:
      - "41006:80"
      - "40006:443"

  doctorssyndicateapi:
       image: ${DOCKER_REGISTRY-}doctorssyndicateapi
       build:
         context: .
         dockerfile: DoctorsSyndicateAPI/Dockerfile
       ports:
        - "41007:80"
        - "40007:443"

  civilpoliceapi:
    image: ${DOCKER_REGISTRY-}civilpoliceapi
    build:
      context: .
      dockerfile: CivilPoliceAPI/Dockerfile
    ports:
      - "41008:80"
      - "40008:443"

  awqafapi:
    image: ${DOCKER_REGISTRY-}awqafapi
    build:
      context: .
      dockerfile: AwqafAPI/Dockerfile
    ports:
      - "41010:80"
      - "40010:443"
  courtapi:
    image: ${DOCKER_REGISTRY-}courtapi
    build:
      context: .
      dockerfile: CourtAPI/Dockerfile
    ports:
      - "41012:80"
      - "40012:443"
  defenseapi:
    image: ${DOCKER_REGISTRY-}defenseapi
    build:
      context: .
      dockerfile: DefenseAPI/Dockerfile
    ports:
      - "41013:80"
      - "40013:443"
  militarycollegeapi:
    image: ${DOCKER_REGISTRY-}militarycollegeapi
    build:
      context: .
      dockerfile: MilitaryCollegeAPI/Dockerfile
    ports:
      - "41009:80"
      - "40009:443"
  passportapi:
    image: ${DOCKER_REGISTRY-}passportapi
    build:
      context: .
      dockerfile: PassportAPI/Dockerfile
    ports:
      - "41011:80"
      - "40011:443"

  loginapi:
    image: ${DOCKER_REGISTRY-}loginapi
    build:
      context: .
      dockerfile: LoginAPI/Dockerfile
    ports:
      - "41050:80"
      - "40050:443"

  jailapi:
    image: ${DOCKER_REGISTRY-}jailapi
    build:
      context: .
      dockerfile: JailAPI/Dockerfile
    ports:
      - "41015:80"
      - "40015:443"


  competentauthorityapi:
    image: ${DOCKER_REGISTRY-}competentauthorityapi
    build:
      context: .
      dockerfile: CompetentAuthorityAPI/Dockerfile
    ports:
      - "41016:80"
      - "40016:443"

volumes:
  sqlvol:




