version: '3.4'

services:

  consul:
    image: consul:latest
    container_name: consul_server
    network_mode: bridge
    ports:
      - "8500:8500"
      -  "8600:8600/udp"
    command:  consul agent -dev -server -ui -node=server-1 -bootstrap-expect=1 -client="0.0.0.0"
    deploy:
      resources:
        limits:
          memory: 50M

  sql-server-db:
    container_name: SQL_Server
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sqlvol:/var/opt/mssql
    ports:
      - "1403:1433"
    environment:
      SA_PASSWORD: "r00t.R00T"
      ACCEPT_EULA: "Y"


  healthminapi:
    image: ${DOCKER_REGISTRY-}healthminapi
    build:
      context: .
      dockerfile: HealthMinAPI/Dockerfile
    ports:
      - "41003:80"
      - "40003:443"
    deploy:
      resources:
        limits:
          memory: 50M

  higheduminapi:
    image: ${DOCKER_REGISTRY-}higheduminapi
    build:
      context: .
      dockerfile: HighEduMinAPI/Dockerfile
    ports:
      - "41001:80"
      - "40001:443"
    deploy:
      resources:
        limits:
          memory: 50M

  airlineapi:
    image: ${DOCKER_REGISTRY-}airlineapi
    build:
      context: .
      dockerfile: AirLineAPI/Dockerfile
    ports:
      - "41002:80"
      - "40002:443"
    deploy:
      resources:
        limits:
          memory: 50M

  politicalpartiesapi:
    image: ${DOCKER_REGISTRY-}politicalpartiesapi
    build:
      context: .
      dockerfile: PoliticalPartiesAPI/Dockerfile
    ports:
      - "41004:80"
      - "40004:443"
    deploy:
      resources:
        limits:
          memory: 50M

  bloodbankapi:
    image: ${DOCKER_REGISTRY-}bloodbankapi
    build:
      context: .
      dockerfile: BloodBankAPI/Dockerfile
    ports:
      - "41005:80"
      - "40005:443"
    deploy:
      resources:
        limits:
          memory: 50M

  universityapi:
    image: ${DOCKER_REGISTRY-}universityapi
    build:
      context: .
      dockerfile: UniversityAPI/Dockerfile
    ports:
      - "41006:80"
      - "40006:443"
    deploy:
      resources:
        limits:
          memory: 50M

  doctorssyndicateapi:
       image: ${DOCKER_REGISTRY-}doctorssyndicateapi
       build:
         context: .
         dockerfile: DoctorsSyndicateAPI/Dockerfile
       ports:
        - "41007:80"
        - "40007:443"
       deploy:
         resources:
           limits:
             memory: 50M

  civilpoliceapi:
    image: ${DOCKER_REGISTRY-}civilpoliceapi
    build:
      context: .
      dockerfile: CivilPoliceAPI/Dockerfile
    ports:
      - "41008:80"
      - "40008:443"
    deploy:
      resources:
        limits:
          memory: 50M

  awqafapi:
    image: ${DOCKER_REGISTRY-}awqafapi
    build:
      context: .
      dockerfile: AwqafAPI/Dockerfile
    ports:
      - "41010:80"
      - "40010:443"
    deploy:
      resources:
        limits:
          memory: 50M

  courtapi:
    image: ${DOCKER_REGISTRY-}courtapi
    build:
      context: .
      dockerfile: CourtAPI/Dockerfile
    ports:
      - "41012:80"
      - "40012:443"
    deploy:
      resources:
        limits:
          memory: 50M

  defenseapi:
    image: ${DOCKER_REGISTRY-}defenseapi
    build:
      context: .
      dockerfile: DefenseAPI/Dockerfile
    ports:
      - "41013:80"
      - "40013:443"
    deploy:
      resources:
        limits:
          memory: 50M

  militarycollegeapi:
    image: ${DOCKER_REGISTRY-}militarycollegeapi
    build:
      context: .
      dockerfile: MilitaryCollegeAPI/Dockerfile
    ports:
      - "41009:80"
      - "40009:443"
    deploy:
      resources:
        limits:
          memory: 50M

  passportapi:
    image: ${DOCKER_REGISTRY-}passportapi
    build:
      context: .
      dockerfile: PassportAPI/Dockerfile
    ports:
      - "41011:80"
      - "40011:443"
    deploy:
      resources:
        limits:
          memory: 50M


  jailapi:
    image: ${DOCKER_REGISTRY-}jailapi
    build:
      context: .
      dockerfile: JailAPI/Dockerfile
    ports:
      - "41015:80"
      - "40015:443"
    deploy:
      resources:
        limits:
          memory: 50M

  competentauthorityapi:
    image: ${DOCKER_REGISTRY-}competentauthorityapi
    build:
      context: .
      dockerfile: CompetentAuthorityAPI/Dockerfile
    ports:
      - "41016:80"
      - "40016:443"
    deploy:
      resources:
        limits:
          memory: 50M

  ministryofforeignaffairsapi:
    image: ${DOCKER_REGISTRY-}ministryofforeignaffairsapi
    build:
      context: .
      dockerfile: MinistryOfForeignAffairsAPI/Dockerfile
    ports:
      - "41017:80"
      - "40017:443"
    deploy:
      resources:
        limits:
          memory: 50M

  minestryofinterioraffairsapi:
    image: ${DOCKER_REGISTRY-}minestryofinterioraffairsapi
    build:
      context: .
      dockerfile: MinestryofInteriorAffairsAPI/Dockerfile
    ports:
      - "41014:80"
      - "40014:443"
    deploy:
      resources:
        limits:
          memory: 50M

  barassociationapi:
    image: ${DOCKER_REGISTRY-}barassociationapi
    build:
      context: .
      dockerfile: BarAssociationAPI/Dockerfile
    ports:
      - "41020:80"
      - "40020:443"
    deploy:
      resources:
        limits:
          memory: 50M      

  financeapi:
    image: ${DOCKER_REGISTRY-}financeapi
    build:
      context: .
      dockerfile: FinanceAPI/Dockerfile
    ports:
      - "41022:80"
      - "40022:443"
    deploy:
      resources:
        limits:
          memory: 50M

  eduminapi:
    image: ${DOCKER_REGISTRY-}eduminapi
    build:
      context: .
      dockerfile: EduMinAPI/Dockerfile
    ports:
      - "41021:80"
      - "40021:443"
    deploy:
      resources:
        limits:
          memory: 50M

  laborminapi:
    image: ${DOCKER_REGISTRY-}laborminapi
    build:
      context: .
      dockerfile: LaborMinAPI/Dockerfile
    ports:
      - "41024:80"
      - "40024:443"
    deploy:
      resources:
        limits:
          memory: 50M

  transportationminapi:
    image: ${DOCKER_REGISTRY-}transportationminapi
    build:
      context: .
      dockerfile: TransportationMinAPI/Dockerfile
    ports:
      - "41023:80"
      - "40023:443"
    deploy:
      resources:
        limits:
          memory: 50M

  recordadminstration:
    image: ${DOCKER_REGISTRY-}recordadminstration
    build:
      context: .
      dockerfile: RecordAdminstration/Dockerfile
    ports:
      - "41018:80"
      - "40018:443"
    deploy:
      resources:
        limits:
          memory: 50M


volumes:
  sqlvol:

