version: '3.4'

services:

  consul:
    image: consul:latest
    container_name: consul_server
    network_mode: bridge
    ports:
      - "8500:8500"
      -  "8600:8600/udp"
    command:  consul agent -dev -server -ui -node=server-1 -bootstrap-expect=1 -client="0.0.0.0"

  sql-server-db:
    container_name: SQL_Server
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sqlvol:/var/opt/mssql
    ports:
      - "1403:1433"
    environment:
      SA_PASSWORD: "r00t.R00T"
      ACCEPT_EULA: "Y"

  healthminapi:
    image: ${DOCKER_REGISTRY-}healthminapi
    build:
      context: .
      dockerfile: HealthMinAPI/Dockerfile
    ports:
      - "41003:80"
      - "40003:443"

  higheduminapi:
    image: ${DOCKER_REGISTRY-}higheduminapi
    build:
      context: .
      dockerfile: HighEduMinAPI/Dockerfile
    ports:
      - "41001:80"
      - "40001:443"


  airlineapi:
    image: ${DOCKER_REGISTRY-}airlineapi
    build:
      context: .
      dockerfile: AirLineAPI/Dockerfile
    ports:
      - "41002:80"
      - "40002:443"

  politicalpartiesapi:
    image: ${DOCKER_REGISTRY-}politicalpartiesapi
    build:
      context: .
      dockerfile: PoliticalPartiesAPI/Dockerfile
    ports:
      - "41004:80"
      - "40004:443"

  loginapi:
    image: ${DOCKER_REGISTRY-}loginapi
    build:
      context: .
      dockerfile: LoginAPI/Dockerfile
    ports:
      - "41050:80"
      - "40050:443"


volumes:
  sqlvol:

