// <auto-generated />
using HighEduMinAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HighEduMinAPI.Migrations
{
    [DbContext(typeof(HighEduMinContext))]
    partial class HighEduMinContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HighEduMinAPI.Models.HighEduMin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ChangeCert")
                        .HasColumnType("bit");

                    b.Property<bool>("GovSendToStudy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAStudent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StudyOutSide")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("HighEduMinDBS");
                });
#pragma warning restore 612, 618
        }
    }
}
