// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinestryofInteriorAffairsAPI.Data;

namespace MinestryofInteriorAffairsAPI.Migrations
{
    [DbContext(typeof(MinestryofInteriorAffairsContext))]
    partial class MinestryofInteriorAffairsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinestryofInteriorAffairs.Model.MinestryofInteriorAffairsAPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumofYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MinestryofInteriorAffairsDB");
                });
#pragma warning restore 612, 618
        }
    }
}
