// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PassportAPI.Data;

namespace PassportAPI.Migrations
{
    [DbContext(typeof(PassportContext))]
    [Migration("20221026121445_PasportMig")]
    partial class PasportMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PassportAPI.Model.Passport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Istravel")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfDaysInSideCoun")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDaysOutsideCoun")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PassportDBS");
                });
#pragma warning restore 612, 618
        }
    }
}
