// <auto-generated />
using System;
using BarAssociationAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarAssociationAPI.Migrations
{
    [DbContext(typeof(BarAssociationContext))]
    [Migration("20221019101420_BarAssociationDB")]
    partial class BarAssociationDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BarAssociationAPI.Models.Lawyers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("graduationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("joinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("trainstartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("BarAssociationDB");
                });
#pragma warning restore 612, 618
        }
    }
}
